### ISSUE TITLE
reboot command 🤨

### ISSUE THREAD

**Issue by its-darsh** [cytsai1008/DiscordVoice#71]
![image](https://github.com/cytsai1008/DiscordVoice/assets/129121284/8c74785f-813e-4ec2-b63e-bfeab6ee477c)
there is no way a bot can reboot like this, the process begin killed since it's not a devel process.

~~WHY TF CODE LOOKS LIKE THAT~~

**Comment by its-darsh** [comment]
![image](https://github.com/cytsai1008/DiscordVoice/assets/129121284/cd925de1-d224-478f-bfc9-b439dee9bd17)
bruh i didn't seen that.. 🗿

**Comment by cytsai1008** [comment]
It works because heroku will force restart any process except SIGTERM, I may change it after I changed the hosting platform ~~or someday.~~
